# H2 Local Database
spring.datasource.url=jdbc:h2:mem:donaciones
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration
server.port=${PORT:8084}