# ==============================
# BASE DE DATOS (PostgreSQL)
# Reemplazar con la URL de Render cuando esté deployado
# ==============================
spring.datasource.url=jdbc:h2:mem:logistica_db
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

donaciones.url=${DONACIONES_URL:http://localhost:8081}
donadores.url=${DONADORES_URL:http://localhost:8082}

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ==============================
# MÉTRICAS - Actuator
# ==============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ==============================
# MÉTRICAS - Datadog
# ==============================
management.datadog.metrics.export.api-key=6f37ced2e8b904c9b7895689ab98f880
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=30s
management.metrics.tags.application=logistica
management.metrics.tags.env=production

# DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.add-properties=false

# Server Configuration
server.port=8084
